name: saturn
services:
  db:
    container_name: sat_db
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
  search:
    container_name: sat_search
    image: getmeili/meilisearch
    volumes:
      - search_data:/meili_data
    ports:
      - 7700:7700
  api:
    container_name: sat_api
    build: ./api
    command: start
    environment:
      DB_URL: mongodb://db:27017/main
      SECRET: ${MASTER_KEY}
    ports:
      - 8080:3000
volumes:
  db_data:
  search_data:

